//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwInversion_tenenciaWI
    {
        public int IdInversion { get; set; }
        public string Instrumento { get; set; }
        public string Criptomoneda { get; set; }
        public string CriptomonedaGanada { get; set; }
        public double TasaEstimada { get; set; }
        public double TasaReal { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public double CantidadInvertida { get; set; }
        public Nullable<double> CantidadGanada { get; set; }
        public Nullable<int> Lugar { get; set; }
        public Nullable<int> idTenencia { get; set; }
        public string Exchange { get; set; }
        public string Wallet { get; set; }
        public Nullable<bool> Centralizado { get; set; }
        public Nullable<bool> Nacional { get; set; }
        public Nullable<double> Capital { get; set; }
        public string Ticker { get; set; }
        public string Tipo { get; set; }
    }
}
