//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTenencia
    {
        public int idTenencia { get; set; }
        public string Wallet { get; set; }
        public string Tipo { get; set; }
        public string Semilla { get; set; }
        public string Exchange { get; set; }
        public Nullable<bool> Nacional { get; set; }
        public Nullable<bool> Centralizado { get; set; }
        public string Url { get; set; }
        public string Lugar { get; set; }
    }
}
